#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
"""
import os

import config as cfg0

_FT3_SERVER_VERSION_MAJOR = "0"
_FT3_SERVER_VERSION_MINOR = "4"
_FT3_SERVER_VERSION_POINT = "4"
_FT3_SERVER_VERSION = _FT3_SERVER_VERSION_MAJOR + '.' + _FT3_SERVER_VERSION_MINOR + '.' + _FT3_SERVER_VERSION_POINT

_FT3_SERVER_APP_TITLE = "Visi-Trak FasTrak3 Web Server" + " " + _FT3_SERVER_VERSION

_FT3_SERVER_PANEL_TITLES = ["Alarm State", "Parameters"]


_FT3_SERVER_STREAM_BUTTON_ACTIVE_SYMBOL   = "\N{BLACK RIGHT-POINTING TRIANGLE}"
_FT3_SERVER_STREAM_BUTTON_INACTIVE_SYMBOL = "\N{BLACK CIRCLE}"
_FT3_SERVER_STREAM_BUTTON_ACTIVE_LABEL    = _FT3_SERVER_STREAM_BUTTON_ACTIVE_SYMBOL + " " + "Streaming"
_FT3_SERVER_STREAM_BUTTON_INACTIVE_LABEL  = _FT3_SERVER_STREAM_BUTTON_INACTIVE_SYMBOL + " " + "Paused"

_FT3_SERVER_STREAM_BUTTON_ACTIVE_TYPE = "success"
_FT3_SERVER_STREAM_BUTTON_INACTIVE_TYPE = "default"

_FT3_SERVER_STREAM_BUTTON_PX_W = 100
_FT3_SERVER_STREAM_BUTTON_PX_H = 30
_FT3_SERVER_STREAM_BUTTON_MARGIN = [30, 5, 5, 20]

_FT3_SERVER_STREAM_BUTTON_NAME = "ft3_server_stream_button"


_FT3_SERVER_BANNER_SPACER_PX_W = 100
_FT3_SERVER_BANNER_SPACER_PX_H = 75
_FT3_SERVER_BANNER_SPACER_MARGIN = [5, 5, 5, 5]
_FT3_SERVER_BANNER_SPACER_NAME = "ft3_server_banner_spacer"


_FT3_SERVER_VISITRAK_LOGO_PATHNAME = os.path.join(cfg0._FT3_MAIN_APP_RELPATH,"static")
_FT3_SERVER_VISITRAK_LOGO_FILENAME = "Visi-Trak_logo.png"
_FT3_SERVER_VISITRAK_LOGO = os.path.join(_FT3_SERVER_VISITRAK_LOGO_PATHNAME, _FT3_SERVER_VISITRAK_LOGO_FILENAME)

_FT3_SERVER_VISITRAK_LOGO_DIV_TEXT = """<img src="{:s}" alt="div_image">""".format(_FT3_SERVER_VISITRAK_LOGO)
_FT3_SERVER_VISITRAK_LOGO_DIV_PX_W = 200
_FT3_SERVER_VISITRAK_LOGO_DIV_PX_H = 200
_FT3_SERVER_VISITRAK_LOGO_DIV_MARGIN = [5, 5, 5, 5]
_FT3_SERVER_VISITRAK_LOGO_DIV_NAME = "ft3_server_visitrak_logo_div"
