#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
"""
import numpy as np

from bokeh.transform import transform
from bokeh.models.transforms import CustomJSTransform

import units.units as units


v_func = '''
    var rv = new Float64Array(xs.length)
    for(let i = 0; i < xs.length; i++) {
        rv[i] = xs[i] * <G>
    }
    return rv
'''.replace('<G>', str(units._FT3_UNITS_MPA_TO_PSI))
_tf_press = CustomJSTransform(v_func=v_func)

v_func = '''
    var rv = new Float64Array(xs.length)
    for(let i = 0; i < xs.length; i++) {
        rv[i] = xs[i] * <G>
    }
    return rv
'''.replace('<G>', str(units._FT3_UNITS_MM_TO_IN))
_tf_pv = CustomJSTransform(v_func=v_func)

_FT3_SHOT_LINE_PRESS_HEAD_SI = "press_head"
_FT3_SHOT_LINE_PRESS_HEAD_BG = transform("press_head", _tf_press)

_FT3_SHOT_LINE_PRESS_ROD_SI = "press_rod"
_FT3_SHOT_LINE_PRESS_ROD_BG = transform("press_rod", _tf_press)

_FT3_SHOT_LINE_POS_SI = "pos"
_FT3_SHOT_LINE_POS_BG = transform("pos", _tf_pv)

_FT3_SHOT_LINE_VEL_SI = "vel"
_FT3_SHOT_LINE_VEL_BG = transform("vel", _tf_pv)


_FT3_SHOT_SEL_SHOT_PAD_W_CHAR  = w0 = 12
_FT3_SHOT_SEL_SHOT_SHOT_W_CHAR = w1 = 4
_FT3_SHOT_SEL_SHOT_TIME_W_CHAR = w2 = 23

_FT3_SHOT_SEL_SHOT_DIV_TEXT_FORMAT = """<b>Shot:</b> {:4d}{:s} <b>Start:</b> {:23s} </br> <b>Stop:</b> {:23s}"""
_FT3_SHOT_SEL_SHOT_DIV_TEXT = lambda shot,t0,t1: _FT3_SHOT_SEL_SHOT_DIV_TEXT_FORMAT.format(
        shot[0], '&nbsp;'*(w0),
        t0.dt.strftime("%Y-%m-%d %H:%M:%S.%f")[0][:-3],
        t1.dt.strftime("%Y-%m-%d %H:%M:%S.%f")[0][:-3])
_FT3_SHOT_SEL_SHOT_DIV_TEXT_INIT   = """<b>Shot:</b> {:s} <b>Start:</b> {:s} </br> <b>Stop:</b> {:s}""".format('&nbsp;'*(w0+w1),'&nbsp;'*(w2),'&nbsp;'*(w2))
_FT3_SHOT_SEL_SHOT_DIV_STYLE       = {'text-align':'right', 'font-size':'115%', 'color':'#000000'}

_FT3_SHOT_SEL_SHOT_DIV_PX_W = 440
_FT3_SHOT_SEL_SHOT_DIV_PX_H = 30
_FT3_SHOT_SEL_SHOT_DIV_MARGIN = [35, 5, 5, 5]

_FT3_SHOT_SEL_SHOT_DIV_NAME = "ft3_shot_sel_shot_div"

                                      
_FT3_SHOT_QUAD_PLOT_BASELINE_PX_W = 750

_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_PX_W  = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_W
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_PX_W = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_W // 2
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_PX_W  = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_W
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_PX_W = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_W // 2

_FT3_SHOT_QUAD_PLOT_ARRAY_PX_W = []
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_W += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_PX_W]
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_W += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_PX_W]
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_W += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_PX_W]
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_W += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_PX_W]


_FT3_SHOT_QUAD_PLOT_BASELINE_PX_H = 300

_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_PX_H  = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_H
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_PX_H = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_H
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_PX_H  = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_H
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_PX_H = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_H

_FT3_SHOT_QUAD_PLOT_ARRAY_PX_H = []
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_H += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_PX_H]
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_H += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_PX_H]
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_H += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_PX_H]
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_H += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_PX_H]


_FT3_SHOT_QUAD_PLOT_BASELINE_PX_BORDER = 1

_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_PX_BORDER  = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_BORDER
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_PX_BORDER = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_BORDER
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_PX_BORDER  = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_BORDER
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_PX_BORDER = _FT3_SHOT_QUAD_PLOT_BASELINE_PX_BORDER

_FT3_SHOT_QUAD_PLOT_ARRAY_PX_BORDER = []
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_BORDER += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_PX_BORDER]
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_BORDER += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_PX_BORDER]
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_BORDER += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_PX_BORDER]
_FT3_SHOT_QUAD_PLOT_ARRAY_PX_BORDER += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_PX_BORDER]


_FT3_SHOT_QUAD_PLOT_BASELINE_BACKGROUND = "#000000"

_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_BACKGROUND  = _FT3_SHOT_QUAD_PLOT_BASELINE_BACKGROUND
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_BACKGROUND = _FT3_SHOT_QUAD_PLOT_BASELINE_BACKGROUND
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_BACKGROUND  = _FT3_SHOT_QUAD_PLOT_BASELINE_BACKGROUND
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_BACKGROUND = _FT3_SHOT_QUAD_PLOT_BASELINE_BACKGROUND

_FT3_SHOT_QUAD_PLOT_ARRAY_BACKGROUND = []
_FT3_SHOT_QUAD_PLOT_ARRAY_BACKGROUND += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_BACKGROUND]
_FT3_SHOT_QUAD_PLOT_ARRAY_BACKGROUND += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_BACKGROUND]
_FT3_SHOT_QUAD_PLOT_ARRAY_BACKGROUND += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_BACKGROUND]
_FT3_SHOT_QUAD_PLOT_ARRAY_BACKGROUND += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_BACKGROUND]


_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_X_AXIS_LOC  = None
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_X_AXIS_LOC = None
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_X_AXIS_LOC  = "below"
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_X_AXIS_LOC = "below"

_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LOC = []
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LOC += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_X_AXIS_LOC]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LOC += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_X_AXIS_LOC]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LOC += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_X_AXIS_LOC]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LOC += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_X_AXIS_LOC]


_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_TOOLBAR_LOC  = None
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_TOOLBAR_LOC = None
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_TOOLBAR_LOC  = None
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_TOOLBAR_LOC = None

_FT3_SHOT_QUAD_PLOT_ARRAY_TOOLBAR_LOC = []
_FT3_SHOT_QUAD_PLOT_ARRAY_TOOLBAR_LOC += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_TOOLBAR_LOC]
_FT3_SHOT_QUAD_PLOT_ARRAY_TOOLBAR_LOC += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_TOOLBAR_LOC]
_FT3_SHOT_QUAD_PLOT_ARRAY_TOOLBAR_LOC += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_TOOLBAR_LOC]
_FT3_SHOT_QUAD_PLOT_ARRAY_TOOLBAR_LOC += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_TOOLBAR_LOC]


_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_Y_AXIS_LOC  = "left"
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_Y_AXIS_LOC = "right"
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_Y_AXIS_LOC  = "left"
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_Y_AXIS_LOC = "right"

_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LOC = []
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LOC += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_Y_AXIS_LOC]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LOC += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_Y_AXIS_LOC]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LOC += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_Y_AXIS_LOC]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LOC += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_Y_AXIS_LOC]


_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_X_AXIS_LABEL_BG  = None
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_X_AXIS_LABEL_BG = None
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_X_AXIS_LABEL_BG  = "Position (in)"
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_X_AXIS_LABEL_BG = "Time (ms)"

_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_BG = []
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_BG += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_X_AXIS_LABEL_BG]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_BG += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_X_AXIS_LABEL_BG]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_BG += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_X_AXIS_LABEL_BG]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_BG += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_X_AXIS_LABEL_BG]

_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_X_AXIS_LABEL_SI  = None
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_X_AXIS_LABEL_SI = None
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_X_AXIS_LABEL_SI  = "Position (mm)"
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_X_AXIS_LABEL_SI = "Time (ms)"

_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_SI = []
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_SI += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_X_AXIS_LABEL_SI]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_SI += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_X_AXIS_LABEL_SI]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_SI += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_X_AXIS_LABEL_SI]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_AXIS_LABEL_SI += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_X_AXIS_LABEL_SI]


_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_Y_AXIS_LABEL_BG  = "Pressure (psi)"
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_Y_AXIS_LABEL_BG = "Pressure (psi)"
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_Y_AXIS_LABEL_BG  = "Velocity (in/s)"
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_Y_AXIS_LABEL_BG = "Position (in)"

_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_BG = []
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_BG += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_Y_AXIS_LABEL_BG]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_BG += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_Y_AXIS_LABEL_BG]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_BG += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_Y_AXIS_LABEL_BG]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_BG += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_Y_AXIS_LABEL_BG]

_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_Y_AXIS_LABEL_SI  = "Pressure (MPa)"
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_Y_AXIS_LABEL_SI = "Pressure (MPa)"
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_Y_AXIS_LABEL_SI  = "Velocity (mm/s)"
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_Y_AXIS_LABEL_SI = "Position (mm)"

_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_SI = []
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_SI += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_Y_AXIS_LABEL_SI]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_SI += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_Y_AXIS_LABEL_SI]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_SI += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_Y_AXIS_LABEL_SI]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_AXIS_LABEL_SI += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_Y_AXIS_LABEL_SI]


_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_X_RANGE  = (0.0,1.0)
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_X_RANGE = (0.0,1.0)
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_X_RANGE  = (0.0,1.0)
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_X_RANGE = (0.0,1.0)

_FT3_SHOT_QUAD_PLOT_ARRAY_X_RANGE = []
_FT3_SHOT_QUAD_PLOT_ARRAY_X_RANGE += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_X_RANGE]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_RANGE += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_X_RANGE]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_RANGE += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_X_RANGE]
_FT3_SHOT_QUAD_PLOT_ARRAY_X_RANGE += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_X_RANGE]


_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_Y_RANGE  = (0.0,1.0)
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_Y_RANGE = (0.0,1.0)
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_Y_RANGE  = (0.0,1.0)
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_Y_RANGE = (0.0,1.0)

_FT3_SHOT_QUAD_PLOT_ARRAY_Y_RANGE = []
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_RANGE += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_Y_RANGE]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_RANGE += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_Y_RANGE]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_RANGE += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_Y_RANGE]
_FT3_SHOT_QUAD_PLOT_ARRAY_Y_RANGE += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_Y_RANGE]


_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_TITLE  = None
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_TITLE = None
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_TITLE  = None
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_TITLE = None

_FT3_SHOT_QUAD_PLOT_ARRAY_TITLE = []
_FT3_SHOT_QUAD_PLOT_ARRAY_TITLE += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_TITLE]
_FT3_SHOT_QUAD_PLOT_ARRAY_TITLE += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_TITLE]
_FT3_SHOT_QUAD_PLOT_ARRAY_TITLE += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_TITLE]
_FT3_SHOT_QUAD_PLOT_ARRAY_TITLE += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_TITLE]


_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_NAME  = "ft3_shot_quad_plot_ul"
_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_NAME = "ft3_shot_quad_plot_ur"
_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_NAME  = "ft3_shot_quad_plot_ll"
_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_NAME = "ft3_shot_quad_plot_lr"

_FT3_SHOT_QUAD_PLOT_ARRAY_NAME = []
_FT3_SHOT_QUAD_PLOT_ARRAY_NAME += [_FT3_SHOT_QUAD_PLOT_UPPER_LEFT_NAME]
_FT3_SHOT_QUAD_PLOT_ARRAY_NAME += [_FT3_SHOT_QUAD_PLOT_UPPER_RIGHT_NAME]
_FT3_SHOT_QUAD_PLOT_ARRAY_NAME += [_FT3_SHOT_QUAD_PLOT_LOWER_LEFT_NAME]
_FT3_SHOT_QUAD_PLOT_ARRAY_NAME += [_FT3_SHOT_QUAD_PLOT_LOWER_RIGHT_NAME]


_FT3_SHOT_SEL_LINE_ALPHA = 1.000
_FT3_SHOT_SEL_LINE_WIDTH = 1.500

_FT3_SHOT_REF_LINE_ALPHA = 0.500
_FT3_SHOT_REF_LINE_WIDTH = 5.000


_FT3_JS_HOVER_CODE_X = """
    return special_vars.data_x.toFixed(3)
"""

_FT3_JS_HOVER_CODE_Y = """
    return special_vars.data_y.toFixed(3)
"""


_FT3_SHOT_POS_PRESS_HEAD_LINE_ALPHA = _FT3_SHOT_SEL_LINE_ALPHA
_FT3_SHOT_POS_PRESS_HEAD_LINE_WIDTH = _FT3_SHOT_SEL_LINE_WIDTH
_FT3_SHOT_POS_PRESS_HEAD_LINE_COLOR = "#FFFFFF"
_FT3_SHOT_POS_PRESS_HEAD_LINE_NAME  = "ft3_shot_pos_press_head"

_FT3_SHOT_POS_PRESS_HEAD_HOVER_NAMES    = [_FT3_SHOT_POS_PRESS_HEAD_LINE_NAME]
_FT3_SHOT_POS_PRESS_HEAD_HOVER_TOOLTIPS_BG = [('Position', '@pos{%10.3f} in'),('Head Pressure', '@press_head{%10.3f} psi')]
_FT3_SHOT_POS_PRESS_HEAD_HOVER_TOOLTIPS_SI = [('Position', '@pos{%10.3f} mm'),('Head Pressure', '@press_head{%10.3f} MPa')]
_FT3_SHOT_POS_PRESS_HEAD_HOVER_MODE     = "vline"


_FT3_SHOT_POS_PRESS_ROD_LINE_ALPHA = _FT3_SHOT_SEL_LINE_ALPHA
_FT3_SHOT_POS_PRESS_ROD_LINE_WIDTH = _FT3_SHOT_SEL_LINE_WIDTH
_FT3_SHOT_POS_PRESS_ROD_LINE_COLOR = "#00FFFF"
_FT3_SHOT_POS_PRESS_ROD_LINE_NAME  = "ft3_shot_pos_press_rod"

_FT3_SHOT_POS_PRESS_ROD_HOVER_NAMES    = [_FT3_SHOT_POS_PRESS_ROD_LINE_NAME]
_FT3_SHOT_POS_PRESS_ROD_HOVER_TOOLTIPS_BG = [('Position', '@pos{%10.3f} in'),('Rod Pressure', '@press_rod{%10.3f} psi')]
_FT3_SHOT_POS_PRESS_ROD_HOVER_TOOLTIPS_SI = [('Position', '@pos{%10.3f} mm'),('Rod Pressure', '@press_rod{%10.3f} MPa')]
_FT3_SHOT_POS_PRESS_ROD_HOVER_MODE     = "vline"


_FT3_SHOT_TIME_PRESS_HEAD_LINE_ALPHA = _FT3_SHOT_SEL_LINE_ALPHA
_FT3_SHOT_TIME_PRESS_HEAD_LINE_WIDTH = _FT3_SHOT_SEL_LINE_WIDTH
_FT3_SHOT_TIME_PRESS_HEAD_LINE_COLOR = "#FFFFFF"
_FT3_SHOT_TIME_PRESS_HEAD_LINE_NAME  = "ft3_shot_time_press_head"

_FT3_SHOT_TIME_PRESS_HEAD_HOVER_NAMES    = [_FT3_SHOT_TIME_PRESS_HEAD_LINE_NAME]
_FT3_SHOT_TIME_PRESS_HEAD_HOVER_TOOLTIPS_BG = [('Time', '@t{%10.3f} ms'),('Head Pressure', '@press_head{%10.3f} psi')]
_FT3_SHOT_TIME_PRESS_HEAD_HOVER_TOOLTIPS_SI = [('Time', '@t{%10.3f} ms'),('Head Pressure', '@press_head{%10.3f} MPa')]
_FT3_SHOT_TIME_PRESS_HEAD_HOVER_MODE     = "vline"


_FT3_SHOT_TIME_PRESS_ROD_LINE_ALPHA = _FT3_SHOT_SEL_LINE_ALPHA
_FT3_SHOT_TIME_PRESS_ROD_LINE_WIDTH = _FT3_SHOT_SEL_LINE_WIDTH
_FT3_SHOT_TIME_PRESS_ROD_LINE_COLOR = "#00FFFF"
_FT3_SHOT_TIME_PRESS_ROD_LINE_NAME  = "ft3_shot_time_press_rod"

_FT3_SHOT_TIME_PRESS_ROD_HOVER_NAMES    = [_FT3_SHOT_TIME_PRESS_ROD_LINE_NAME]
_FT3_SHOT_TIME_PRESS_ROD_HOVER_TOOLTIPS_BG = [('Time', '@t{%10.3f} ms'),('Rod Pressure', '@press_rod{%10.3f} psi')]
_FT3_SHOT_TIME_PRESS_ROD_HOVER_TOOLTIPS_SI = [('Time', '@t{%10.3f} ms'),('Rod Pressure', '@press_rod{%10.3f} MPa')]
_FT3_SHOT_TIME_PRESS_ROD_HOVER_MODE     = "vline"


_FT3_SHOT_POS_VEL_LINE_ALPHA = _FT3_SHOT_SEL_LINE_ALPHA
_FT3_SHOT_POS_VEL_LINE_WIDTH = _FT3_SHOT_SEL_LINE_WIDTH
_FT3_SHOT_POS_VEL_LINE_COLOR = "#00FF00"
_FT3_SHOT_POS_VEL_LINE_NAME  = "ft3_shot_pos_vel"

_FT3_SHOT_POS_VEL_HOVER_NAMES    = [_FT3_SHOT_POS_VEL_LINE_NAME]
_FT3_SHOT_POS_VEL_HOVER_TOOLTIPS_BG = [('Position', '@pos{%10.3f} in'),('Velocity', '@vel{%10.3f} in/s')]
_FT3_SHOT_POS_VEL_HOVER_TOOLTIPS_SI = [('Position', '@pos{%10.3f} mm'),('Velocity', '@vel{%10.3f} mm/s')]
_FT3_SHOT_POS_VEL_HOVER_MODE     = "vline"


_FT3_SHOT_TIME_POS_LINE_ALPHA = _FT3_SHOT_SEL_LINE_ALPHA
_FT3_SHOT_TIME_POS_LINE_WIDTH = _FT3_SHOT_SEL_LINE_WIDTH
_FT3_SHOT_TIME_POS_LINE_COLOR = "#FFFF00"
_FT3_SHOT_TIME_POS_LINE_NAME  = "ft3_shot_time_pos"

_FT3_SHOT_TIME_POS_HOVER_NAMES    = [_FT3_SHOT_TIME_POS_LINE_NAME]
_FT3_SHOT_TIME_POS_HOVER_TOOLTIPS_BG = [('Time', '@t{%10.3f} ms'),('Position', '@pos{%10.3f} in')]
_FT3_SHOT_TIME_POS_HOVER_TOOLTIPS_SI = [('Time', '@t{%10.3f} ms'),('Position', '@pos{%10.3f} mm')]
_FT3_SHOT_TIME_POS_HOVER_MODE     = "vline"


_FT3_REF_POS_PRESS_HEAD_LINE_ALPHA = _FT3_SHOT_REF_LINE_ALPHA
_FT3_REF_POS_PRESS_HEAD_LINE_WIDTH = _FT3_SHOT_REF_LINE_WIDTH
_FT3_REF_POS_PRESS_HEAD_LINE_COLOR = "#E41A1C"
_FT3_REF_POS_PRESS_HEAD_LINE_NAME  = "ft3_ref_pos_press_head"


_FT3_REF_POS_PRESS_ROD_LINE_ALPHA = _FT3_SHOT_REF_LINE_ALPHA
_FT3_REF_POS_PRESS_ROD_LINE_WIDTH = _FT3_SHOT_REF_LINE_WIDTH
_FT3_REF_POS_PRESS_ROD_LINE_COLOR = "#E41A1C"
_FT3_REF_POS_PRESS_ROD_LINE_NAME  = "ft3_rev_pos_press_rod"


_FT3_REF_TIME_PRESS_HEAD_LINE_ALPHA = _FT3_SHOT_REF_LINE_ALPHA
_FT3_REF_TIME_PRESS_HEAD_LINE_WIDTH = _FT3_SHOT_REF_LINE_WIDTH
_FT3_REF_TIME_PRESS_HEAD_LINE_COLOR = "#E41A1C"
_FT3_REF_TIME_PRESS_HEAD_LINE_NAME  = "ft3_ref_time_press_head"


_FT3_REF_TIME_PRESS_ROD_LINE_ALPHA = _FT3_SHOT_REF_LINE_ALPHA
_FT3_REF_TIME_PRESS_ROD_LINE_WIDTH = _FT3_SHOT_REF_LINE_WIDTH
_FT3_REF_TIME_PRESS_ROD_LINE_COLOR = "#E41A1C"
_FT3_REF_TIME_PRESS_ROD_LINE_NAME  = "ft3_ref_time_press_rod"


_FT3_REF_POS_VEL_LINE_ALPHA = _FT3_SHOT_REF_LINE_ALPHA
_FT3_REF_POS_VEL_LINE_WIDTH = _FT3_SHOT_REF_LINE_WIDTH
_FT3_REF_POS_VEL_LINE_COLOR = "#E41A1C"
_FT3_REF_POS_VEL_LINE_NAME  = "ft3_ref_pos_vel"


_FT3_REF_TIME_POS_LINE_ALPHA = _FT3_SHOT_REF_LINE_ALPHA
_FT3_REF_TIME_POS_LINE_WIDTH = _FT3_SHOT_REF_LINE_WIDTH
_FT3_REF_TIME_POS_LINE_COLOR = "#E41A1C"
_FT3_REF_TIME_POS_LINE_NAME  = "ft3_ref_time_pos"


_FT3_SHOT_EVENTS_TABLE_HEADER_DIV_TEXT   = '<b>Shot Events</b>'
_FT3_SHOT_EVENTS_TABLE_HEADER_DIV_STYLE  = {"text-align":"left", "font-size":"115%", "color":"#1F77B4"}
_FT3_SHOT_EVENTS_TABLE_HEADER_DIV_PX_W   = 400
_FT3_SHOT_EVENTS_TABLE_HEADER_DIV_PX_H   = 30
_FT3_SHOT_EVENTS_TABLE_HEADER_DIV_MARGIN = [15, 5, 5, 5]
_FT3_SHOT_EVENTS_TABLE_HEADER_DIV_NAME   = "ft3_shot_events_table_header_div"


_FT3_SHOT_EVENTS_TABLE_FIELDS = ["t","event"]
_FT3_SHOT_EVENTS_TABLE_TITLES = ["Timestamp","Event"]

_FT3_SHOT_EVENTS_TABLE_REORDERABLE = False
_FT3_SHOT_EVENTS_TABLE_SORTABLE    = False

_FT3_SHOT_EVENTS_TABLE_WIDTHS = [115, 285]
_FT3_SHOT_EVENTS_TABLE_PX_ROW = 30
_FT3_SHOT_EVENTS_TABLE_MARGIN = [5, 5, 5, 5]

_FT3_SHOT_EVENTS_TABLE_PX_W = np.sum(_FT3_SHOT_EVENTS_TABLE_WIDTHS)
_FT3_SHOT_EVENTS_TABLE_PX_H = 400

_FT3_SHOT_EVENTS_TABLE_HEADER_ROW = True

_FT3_SHOT_EVENTS_TABLE_INDEX_HEADER   = None
_FT3_SHOT_EVENTS_TABLE_INDEX_POSITION = None

_FT3_SHOT_EVENTS_TABLE_FORMAT = []
_FT3_SHOT_EVENTS_TABLE_FORMAT += ["%Y-%m-%d %H:%M:%S"]
_FT3_SHOT_EVENTS_TABLE_FORMAT += [None]

_FT3_SHOT_EVENTS_TABLE_NAME = "ft3_shot_events_table"


_FT3_SHOT_REF_HEADER_DIV_TEXT   = '<b>Reference Shot</b>'
_FT3_SHOT_REF_HEADER_DIV_STYLE  = {"text-align":"left", "font-size":"115%", "color":"#1F77B4"}
_FT3_SHOT_REF_HEADER_DIV_PX_W   = 135
_FT3_SHOT_REF_HEADER_DIV_PX_H   = 30
_FT3_SHOT_REF_HEADER_DIV_MARGIN = [35, 5, 5, 5]
_FT3_SHOT_REF_HEADER_DIV_NAME   = "ft3_shot_ref_header_div"


_FT3_SHOT_REF_VIEW_CHECKBOX_PX_W   = 50
_FT3_SHOT_REF_VIEW_CHECKBOX_PX_H   = 30
_FT3_SHOT_REF_VIEW_CHECKBOX_MARGIN = [35, 5, 5, 15]

_FT3_SHOT_REF_VIEW_CHECKBOX_LABELS = ["View"]
_FT3_SHOT_REF_VIEW_CHECKBOX_ACTIVE = []

_FT3_SHOT_REF_VIEW_CHECKBOX_NAME   = "ft3_shot_ref_view_checkbox"


_FT3_SHOT_REF_SAVE_BUTTON_LABEL = "Save"

_FT3_SHOT_REF_SAVE_BUTTON_TYPE_ENABLED  = "primary"
_FT3_SHOT_REF_SAVE_BUTTON_TYPE_DISABLED = "default"
_FT3_SHOT_REF_SAVE_BUTTON_DISABLED_INIT = True

_FT3_SHOT_REF_SAVE_BUTTON_PX_W   = 100
_FT3_SHOT_REF_SAVE_BUTTON_PX_H   = 30
_FT3_SHOT_REF_SAVE_BUTTON_MARGIN = [30, 5, 5, 15]

_FT3_SHOT_REF_SAVE_BUTTON_NAME   = "ft3_shot_ref_save_button"
