#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
"""
import numpy as np

from enum import IntEnum,unique

import units.units as units


_FT3_AD_DATA_BITS   = 12
_FT3_AD_DATA_BITS_H = _FT3_AD_DATA_BITS - 1

_FT3_AD_DATA_RESOLUTION = (1 << _FT3_AD_DATA_BITS)
_FT3_AD_DATA_BITMASK   = np.int16(_FT3_AD_DATA_RESOLUTION - 1)

# A/D unsigned and signed (twos-complement) unpacking lambda functions
_FT3_AD_DATA_UNSIGNED = lambda x: (x & _FT3_AD_DATA_BITMASK)
_FT3_AD_DATA_SIGNED   = lambda x: (x & _FT3_AD_DATA_BITMASK) - (1 << _FT3_AD_DATA_BITS) if x & (1 << _FT3_AD_DATA_BITS_H) else (x & _FT3_AD_DATA_BITMASK)


@unique
class SensorType(IntEnum):
    unmapped    = 0
    general     = 1
    pressure    = 2
    temperature = 3
    command     = 4
    num_type    = 5

@unique
class ADMode(IntEnum):
    unsigned = 0
    signed   = 1
    num_mode = 2


_FT3_AD_CHANNEL_PREFIX = 'ana_ch'
_FT3_AD_CHANNEL_NAME   = lambda c: _FT3_AD_CHANNEL_PREFIX+'{:}'.format(c+1)

_FT3_AD_CHANNELS_NUM = 32

_FT3_AD_CHANNELS_ATTRIBUTES_NAMES = []
_FT3_AD_CHANNELS_ATTRIBUTES_NAMES += ['sensor_name']
_FT3_AD_CHANNELS_ATTRIBUTES_NAMES += ['sensor_type']
_FT3_AD_CHANNELS_ATTRIBUTES_NAMES += ['ad_mode']
_FT3_AD_CHANNELS_ATTRIBUTES_NAMES += ['volts_min']
_FT3_AD_CHANNELS_ATTRIBUTES_NAMES += ['volts_max']
_FT3_AD_CHANNELS_ATTRIBUTES_NAMES += ['engr_data_min']
_FT3_AD_CHANNELS_ATTRIBUTES_NAMES += ['engr_data_max']
_FT3_AD_CHANNELS_ATTRIBUTES_NAMES += ['is_press_head']
_FT3_AD_CHANNELS_ATTRIBUTES_NAMES += ['is_press_rod']


_FT3_AD_CHANNELS_SENSOR_NAME_DEFAULT   = ''
_FT3_AD_CHANNELS_SENSOR_TYPE_DEFAULT   = SensorType.unmapped
_FT3_AD_CHANNELS_AD_MODE_DEFAULT       = ADMode.unsigned
_FT3_AD_CHANNELS_VOLTS_MIN_DEFAULT     = 0.00
_FT3_AD_CHANNELS_VOLTS_MAX_DEFAULT     = 5.00
_FT3_AD_CHANNELS_ENGR_DATA_MIN_DEFAULT = 0.00
_FT3_AD_CHANNELS_ENGR_DATA_MAX_DEFAULT = 1.00
_FT3_AD_CHANNELS_PRESS_HEAD_DEFAULT    = False
_FT3_AD_CHANNELS_PRESS_ROD_DEFAULT     = False

_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT = []
_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT += [_FT3_AD_CHANNELS_SENSOR_NAME_DEFAULT]
_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT += [_FT3_AD_CHANNELS_SENSOR_TYPE_DEFAULT]
_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT += [_FT3_AD_CHANNELS_AD_MODE_DEFAULT]
_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT += [_FT3_AD_CHANNELS_VOLTS_MIN_DEFAULT]
_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT += [_FT3_AD_CHANNELS_VOLTS_MAX_DEFAULT]
_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT += [_FT3_AD_CHANNELS_ENGR_DATA_MIN_DEFAULT]
_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT += [_FT3_AD_CHANNELS_ENGR_DATA_MAX_DEFAULT]
_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT += [_FT3_AD_CHANNELS_PRESS_HEAD_DEFAULT]
_FT3_AD_CHANNELS_ATTRIBUTES_DEFAULT += [_FT3_AD_CHANNELS_PRESS_ROD_DEFAULT]


# Default head- and rod- pressure sensor definitions
_FT3_AD_PRESSURE_HEAD_CHANNEL_DEFAULT = 0
_FT3_AD_PRESSURE_ROD_CHANNEL_DEFAULT  = 1

_FT3_AD_PRESSURE_HEAD_VOLTS_MIN_DEFAULT = _FT3_AD_PRESSURE_ROD_VOLTS_MIN_DEFAULT = 0.00
_FT3_AD_PRESSURE_HEAD_VOLTS_MAX_DEFAULT = _FT3_AD_PRESSURE_ROD_VOLTS_MAX_DEFAULT = 0.00

_FT3_AD_PRESSURE_HEAD_PSI_MIN_DEFAULT = _FT3_AD_PRESSURE_ROD_PSI_MIN_DEFAULT = _PMIN = 0.00
_FT3_AD_PRESSURE_HEAD_PSI_MAX_DEFAULT = _FT3_AD_PRESSURE_ROD_PSI_MAX_DEFAULT = _PMAX = 10000.00

_FT3_AD_PRESSURE_HEAD_AD_MODE_DEFAULT = _FT3_AD_CHANNELS_AD_MODE_DEFAULT
_FT3_AD_PRESSURE_ROD_AD_MODE_DEFAULT  = _FT3_AD_CHANNELS_AD_MODE_DEFAULT

_FT3_AD_PRESSURE_HEAD_PSI_PER_BIT = (_PMAX - _PMIN)/_FT3_AD_DATA_RESOLUTION
_FT3_AD_PRESSURE_ROD_PSI_PER_BIT  = (_PMAX - _PMIN)/_FT3_AD_DATA_RESOLUTION

_FT3_AD_PRESSURE_HEAD_MPA_PER_BIT = _FT3_AD_PRESSURE_HEAD_PSI_PER_BIT / units._FT3_UNITS_MPA_TO_PSI
_FT3_AD_PRESSURE_ROD_MPA_PER_BIT = _FT3_AD_PRESSURE_ROD_PSI_PER_BIT / units._FT3_UNITS_MPA_TO_PSI
